name: Artifacts
description: Upload and download artifacts
author: https://github.com/buildkite
requirements:
  - bash
configuration:
  definitions:
    from-to-object:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        step:
          type: string
        build:
          type: string
      required:
        - from
  properties:
    upload:
      oneOf:
        - $ref: '#/definitions/from-to-object'
        - type: string
        - type: array
          items:
            type: string
        - type: array
          items:
            $ref: '#/definitions/from-to-object'
    download:
      oneOf:
        - $ref: '#/definitions/from-to-object'
        - type: string
        - type: array
          items:
            type: string
        - type: array
          items:
            $ref: '#/definitions/from-to-object'
    step:
      type: string
    build:
      type: string
    s3-upload-acl:
      type: string
    gs-upload-acl:
      type: string
    compressed:
      type: string
      pattern: '.*(.zip|.tgz)$'
    ignore-missing:
      type: boolean
    skip-on-status:
      oneOf:
        - type: integer
        - type: array
          items:
            type: integer
  oneOf:
    - required:
      - upload
    - required:
      - download
  dependencies:
    skip-on-status: [ upload ]
  additionalProperties: false
