steps:
  - label: "🤡 :hammer:"
    plugins:
      - docker-compose#v3.9.0:
          run: tests
  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.0.0:
          id: artifacts
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.2.0:
          files: hooks/**
