steps:
  - label: "🤡 :hammer:"
    plugins:
      - plugin-tester#v1.2.0: ~

  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: artifacts

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files: hooks/**

  - label: "Security Scan"
    key: security_scan
    plugins:
      - secrets#v1.0.0:
          variables:
            GITHUB_TOKEN: GITHUB_TOKEN
      - ossf-scorecard#v1.0.0:
          github_token: $$GITHUB_TOKEN

  - wait: ~

  - label: test uploading
    key: upload
    command: echo 'testing artifact upload'
    plugins:
      ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        upload: '.buildkite/pipeline.yml'
    
  - label: test compressed uploading
    key: upload-compressed
    command: echo 'testing compressed artifact upload'
    plugins:
      ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        upload: '.buildkite/pipeline.yml'
        compressed: artifact.tgz
  
  - label: test downloading
    depends_on: upload
    plugins:
      ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        download:
          from: '.buildkite/pipeline.yml'
          to: 'test-pipeline.yml'
    command: test -e test-pipeline.yml
    
  - label: test compressed downloading
    depends_on: upload-compressed
    plugins:
      ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        download:
          from: '.buildkite/pipeline.yml'
          to: 'test-pipeline.yml'
        compressed: artifact.tgz
    command: test -e test-pipeline.yml
