#!/bin/bash
set -euo pipefail

debug_mode='off'
if [[ "${BUILDKITE_PLUGIN_ARTIFACTS_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  debug_mode='on'
  set -x
fi

args=()

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_JOB:-}" ]] ; then
  args+=("--job" "${BUILDKITE_PLUGIN_ARTIFACTS_JOB}")
fi

paths=()

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD:-}" ]] ; then
  paths+=("$BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD")
fi

while IFS='=' read -r path _ ; do
  if [[ $path =~ ^(BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_[0-9]+) ]] ; then
    paths+=("${!path}")
  fi
done < <(env | sort)

workdir=${BUILDKITE_PLUGIN_ARTIFACTS_WORKDIR:-.}

pushd "${workdir}"
trap popd EXIT

if [ "${#paths[@]}" -gt 0 ]; then
  if [ "${#args[@]}" -gt 0 ]; then
    echo "--- Uploading artifacts with args: ${args[*]}"

    buildkite-agent artifact upload "${args[@]}" "$(IFS=, ; echo "${paths[*]}")"
  else
    echo "--- Uploading artifacts"

    buildkite-agent artifact upload "$(IFS=, ; echo "${paths[*]}")"
  fi
fi
