#!/bin/bash
set -eo pipefail

if [[ "${BUILDKITE_PLUGIN_ARTIFACTS_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  set -x
fi

args=()

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_JOB:-}" ]] ; then
  args+=("--job" "${BUILDKITE_PLUGIN_ARTIFACTS_JOB}")
fi

paths=()

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD:-}" ]] ; then
  paths+=("$BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD")
elif [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM:-}" ]] && [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO:-}" ]] ; then
  paths+=("$BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM")
fi

while IFS='=' read -r path _ ; do
  if [[ $path =~ ^(BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_[0-9]+) ]] && ! [[ $path =~ ^(BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_[0-9]_TO+) ]]; then
    paths+=("${!path}")
  fi
done < <(env | sort)

workdir=${BUILDKITE_PLUGIN_ARTIFACTS_WORKDIR:-.}

pushd "${workdir}"
trap popd EXIT

if [ "${#paths[@]}" -eq 1 ]; then
  if ! [[ -z ${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM} ]] && ! [[ -z ${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO} ]]; then
    if [ -f ${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM} ]; then
      echo "--- Moving [${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM}] to [${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO}]..."
      mv "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM}" "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO}"
    fi
    path="${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO}"
  else
    path="${paths[*]}"
  fi

  if [ "${#args[@]}" -gt 0 ]; then
    echo "--- Uploading artifacts with args: ${args[*]}"

    buildkite-agent artifact upload "${args[@]}" "${path}"
  else
    echo "--- Uploading artifacts"

    buildkite-agent artifact upload "${path}"
  fi
elif [ "${#paths[@]}" -gt 1 ]; then
  if [ "${#args[@]}" -gt 0 ]; then
    echo "--- Uploading artifacts with args: ${args[*]}"

    for path in "${paths[@]}"
      do
        if ! [[ -z ${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM} ]] && ! [[ -z ${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO} ]]; then
          if [ -f ${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM} ]; then
            echo "--- Moving [${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM}] to [${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO}]..."
            mv "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM}" "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO}"
          fi
          path="${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO}"
        else
          path="${paths[*]}"
        fi
        buildkite-agent artifact upload "${args[@]}" "$path"
      done
  else
    echo "--- Uploading artifacts"

    for path in "${paths[@]}"
      do
        if ! [[ -z ${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM} ]] && ! [[ -z ${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO} ]]; then
          if [ -f ${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM} ]; then
            echo "--- Moving [${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM}] to [${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO}]..."
            mv "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_FROM}" "${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO}"
          fi
          path="${BUILDKITE_PLUGIN_ARTIFACTS_UPLOAD_TO}"
        else
          path="${paths[*]}"
        fi
        buildkite-agent artifact upload "$path"
      done
  fi
fi