#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_ARTIFACTS_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "~~~ :hammer: Enabling debug mode"
  set -x
fi

step_option="${BUILDKITE_PLUGIN_ARTIFACTS_STEP:-}"
build_option="${BUILDKITE_PLUGIN_ARTIFACTS_BUILD:-}"

paths=()
compress=()

COMPRESSED="false"
SINGULAR_DOWNLOAD_OBJECT="false"
MULTIPLE_DOWNLOADS="false"

# expand variables in the variable name referenced
# DANGEROUS due to the use of eval
# assumes that the environment variable name exists
expand_vars() {
  if [[ ${BUILDKITE_PLUGIN_ARTIFACTS_EXPAND_DOWNLOAD_VARS:-false} != "false" ]]; then
    # expand the variable
    eval echo "${!1}"
  else
    echo "${!1}"
  fi
}

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD:-}" ]] || { [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM:-}" ]] && [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO:-}" ]]; }; then
    SINGULAR_DOWNLOAD_OBJECT="true"
    if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD:-}" ]] ; then
      paths+=("$(expand_vars BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD)")
    elif [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM:-}" ]] && [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO:-}" ]] ; then
      paths+=("$(expand_vars BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM)")
    fi
fi

while IFS='=' read -r path _ ; do
  if [[ $path =~ ^(BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_[0-9]+)$ ]] || [[ $path =~ ^(BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_[0-9]+_FROM)$ ]]; then
    MULTIPLE_DOWNLOADS="true"
    paths+=("$(expand_vars "${path}")")
  fi
done < <(env | sort)

if [[ "${#paths[@]}" -le 0 ]]; then
  # no download data
  exit 0
fi

bk_agent() {
  # first two options must be step and build (but can be empty)
  step="${1}"
  shift
  build="${1}"
  shift

  options=('download')
  if [ -n "$step" ]; then
    options+=("--step" "${step}")
  fi

  if [ -n "$build" ]; then
    options+=("--build" "${build}")
  fi

  if [[ "${#options[@]}" -gt 1 ]]; then
    EXTRA_MESSAGE="(extra args: '${options[*]:1}')"
  else
    EXTRA_MESSAGE=""
  fi

  options+=("${@}")  # all the rest

  echo "~~~ Downloading artifacts ${EXTRA_MESSAGE}"
  buildkite-agent artifact "${options[@]}"
}

handle_bk_error() {
  local filename="$1"
  if [[ "${BUILDKITE_PLUGIN_ARTIFACTS_IGNORE_MISSING:-"false"}" != "false" ]]; then
    echo "Ignoring error in download of ${filename}"
  else
    echo "Error in download of ${filename}"
    exit 1
  fi
}

handle_relocation() {
  local index="$1"
  local var_string=""
  if [[ -n "${index}" ]]; then
    var_string="${index}_"
  fi

  source_env_var="BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_${var_string}FROM"
  dest_env_var="BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_${var_string}TO"
  if [[ -n "${!dest_env_var:-}" ]]; then
    SOURCE_FILE="$(expand_vars "${source_env_var}")"
    DEST_FILE="$(expand_vars "${dest_env_var}")"
    if ! [[ -d "$(dirname "${DEST_FILE}")" ]]; then
      mkdir -p "$(dirname "${DEST_FILE}")"
    fi

    if [[ ! -e "${SOURCE_FILE}" ]] && [[ ${BUILDKITE_PLUGIN_ARTIFACTS_IGNORE_MISSING:-"false"} != "false" ]]; then
      echo "Ignoring missing file ${SOURCE_FILE} for relocation"
    else
      echo "~~~ Moving [${SOURCE_FILE}] to [${DEST_FILE}]..."
      mv "${SOURCE_FILE}" "${DEST_FILE}"
    fi
  fi
}

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_COMPRESSED:-}" ]]; then
  COMPRESSED="true"
  COMPRESSED_FILENAME="$(expand_vars BUILDKITE_PLUGIN_ARTIFACTS_COMPRESSED)"
  if [[ "${COMPRESSED_FILENAME}" =~ .*\.zip ]]; then
    compress+=("unzip" "${COMPRESSED_FILENAME}")
  elif [[ "${COMPRESSED_FILENAME}" =~ .*\.tgz ]]; then
    compress+=("tar" "xzf" "${COMPRESSED_FILENAME}")
  else
    echo "+++ 🚨 The inferred compression file format for the artifact is not currently supported"
    exit 1
  fi
fi

workdir="${BUILDKITE_PLUGIN_ARTIFACTS_WORKDIR:-.}"

if [[ "${COMPRESSED}" == "true" ]]; then
  if ! bk_agent "${step_option}" "${build_option}" "${COMPRESSED_FILENAME}" "${workdir}"; then
    handle_bk_error "${COMPRESSED_FILENAME}"
  else
    echo "~~~ Uncompressing ${paths[*]} from ${COMPRESSED_FILENAME}"
    "${compress[@]}" "${paths[@]}"

    # single relocation
    handle_relocation ""

    # multiple relocations
    index=0
    for path in "${paths[@]}"; do
      handle_relocation "${index}"
      ((index+=1))
    done
  fi

elif [[ "${SINGULAR_DOWNLOAD_OBJECT}" == "true" ]]; then
  source="${paths[*]}"

  if ! bk_agent "${step_option}" "${build_option}" "${source}" "${workdir}"; then
    handle_bk_error "${source}"
  else
    handle_relocation ""
  fi
elif [[ "${MULTIPLE_DOWNLOADS}" == "true" ]]; then
  index=0

  for path in "${paths[@]}"; do
    env_var_base="BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_${index}"
    dest_env_var="${env_var_base}_TO"
    step_env_var="${env_var_base}_STEP"
    build_env_var="${env_var_base}_BUILD"

    # could use $path directly, but would break the ordering because 0,1,10,11,2,20,3 :(
    # may be solved by using sort -V but it is GNU-specific
    if [ -z "${!env_var_base:-}" ]; then
      source_env_var="${env_var_base}_FROM"
    else
      source_env_var="${env_var_base}"
    fi

    source="$(expand_vars "${source_env_var}")"

    if ! bk_agent "${!step_env_var:-${step_option}}" "${!build_env_var:-${build_option}}" "${source}" "${workdir}"; then
      handle_bk_error "${source}"
    else
      handle_relocation "${index}"
    fi

    ((index+=1))
  done
fi
