#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

. "$DIR/../lib/shared.bash"

if [[ -z "${BUILDKITE_PLUGIN_ARTIFACTS_WORKDIR:-}" ]] ; then
  BUILDKITE_PLUGIN_ARTIFACTS_WORKDIR="."
fi

paths=()

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACT_DOWNLOAD:-}" ]] ; then
  paths+=("$BUILDKITE_PLUGIN_ARTIFACT_DOWNLOAD")
fi

while IFS='=' read -r path _ ; do
  if [[ $path =~ ^(BUILDKITE_PLUGIN_ARTIFACT_DOWNLOAD_[0-9]+) ]] ; then
    paths+=("${!path}")
  fi
done < <(env | sort)


if [ "${#paths[@]}" -gt 0 ]; then
  echo "--- Downloading artifacts"
  buildkite-agent artifact download "$(IFS=, ; echo "${paths[*]}")" "${BUILDKITE_PLUGIN_ARTIFACTS_WORKDIR}"
fi
